# Generated by Django 5.2.7 on 2025-11-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('estado_usuario', models.CharField(db_column='estado_usuario', max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Usuario',
                'verbose_name_plural': 'Estados de Usuario',
            },
        ),
        migrations.CreateModel(
            name='EstatusCredito',
            fields=[
                ('estatus_credito', models.CharField(db_column='estatus_credito', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Estatus de Crédito',
                'verbose_name_plural': 'Estatus de Crédito',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.SmallIntegerField(db_column='id_periodo', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('presentacion', models.CharField(db_column='presentacion', max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
            },
        ),
        migrations.CreateModel(
            name='ResultadoVisita',
            fields=[
                ('resultado_visita', models.CharField(db_column='resultado_visita', max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Resultado de Visita',
                'verbose_name_plural': 'Resultados de Visita',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol', models.CharField(db_column='rol', max_length=40, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='TiempoCliente',
            fields=[
                ('id_tiempo_cliente', models.SmallIntegerField(db_column='id_tiempo_cliente', primary_key=True, serialize=False)),
                ('minutos', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tiempo de Cliente',
                'verbose_name_plural': 'Tiempos de Cliente',
            },
        ),
    ]
