# Generated by Django 5.2.7 on 2025-11-04 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('dpi', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo_electronico', models.EmailField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nivel_exito', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('nit', models.CharField(db_column='nit', max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=150, null=True)),
                ('estatus_credito', models.ForeignKey(db_column='estatus_credito', default='B', on_delete=django.db.models.deletion.PROTECT, to='core.estatuscredito')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('presentacion', models.ForeignKey(db_column='presentacion', on_delete=django.db.models.deletion.PROTECT, to='core.presentacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['descripcion'],
            },
        ),
    ]
