# Generated by Django 5.2.7 on 2025-11-04 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=80, unique=True)),
                ('contrasena_hash', models.BinaryField(db_column='contrasena_hash', max_length='max')),
                ('contrasena_salt', models.BinaryField(db_column='contrasena_salt', max_length='max')),
                ('ultimo_ingreso', models.DateTimeField(blank=True, db_column='ultimo_ingreso', null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('dpi', models.CharField(db_column='dpi', max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo_electronico', models.EmailField(blank=True, db_column='correo_electronico', max_length=150, null=True)),
                ('id_usuario', models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrador', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEstado',
            fields=[
                ('id_usuario_estado', models.AutoField(db_column='id_usuario_estado', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, db_column='fecha_inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, db_column='fecha_fin', null=True)),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('estado_usuario', models.ForeignKey(db_column='estado_usuario', on_delete=django.db.models.deletion.PROTECT, to='core.estadousuario')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Estado de Usuario',
                'verbose_name_plural': 'Estados de Usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True, db_column='asignado_en')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('rol', models.ForeignKey(db_column='rol', on_delete=django.db.models.deletion.PROTECT, to='core.rol')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'unique_together': {('id_usuario', 'rol')},
            },
        ),
    ]
