# Generated by Django 5.2.7 on 2025-11-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena_hash',
            field=models.BinaryField(db_column='contrasena_hash'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena_salt',
            field=models.BinaryField(db_column='contrasena_salt'),
        ),
    ]
