# Generated by Django 5.2.7 on 2025-11-04 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaVendedor',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('id_meta', models.AutoField(db_column='id_meta', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(db_column='fecha_inicio')),
                ('fecha_fin', models.DateField(db_column='fecha_fin')),
                ('monto_meta', models.DecimalField(db_column='monto_meta', decimal_places=2, max_digits=14)),
                ('monto_logrado', models.DecimalField(db_column='monto_logrado', decimal_places=2, default=0, max_digits=14)),
                ('peso_conversion', models.SmallIntegerField(db_column='peso_conversion', default=60)),
                ('peso_monto', models.SmallIntegerField(db_column='peso_monto', default=40)),
                ('estado', models.CharField(default='ACTIVA', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('dpi_vendedor', models.ForeignKey(db_column='dpi_vendedor', on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='maestros.vendedor')),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.PROTECT, to='core.periodo')),
            ],
            options={
                'verbose_name': 'Meta de Vendedor',
                'verbose_name_plural': 'Metas de Vendedor',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('id_ruta', models.AutoField(db_column='id_ruta', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('kilometros_estimados', models.DecimalField(blank=True, db_column='kilometros_estimados', decimal_places=2, max_digits=8, null=True)),
                ('tiempo_planificado_min', models.IntegerField(blank=True, db_column='tiempo_planificado_min', null=True)),
                ('tiempo_real_min', models.IntegerField(blank=True, db_column='tiempo_real_min', null=True)),
                ('resultado_global', models.CharField(blank=True, db_column='resultado_global', max_length=50, null=True)),
                ('dpi_vendedor', models.ForeignKey(db_column='dpi_vendedor', on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='maestros.vendedor')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RutaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_visita', models.IntegerField(db_column='orden_visita')),
                ('hora_inicio', models.DateTimeField(blank=True, db_column='hora_inicio', null=True)),
                ('hora_fin', models.DateTimeField(blank=True, db_column='hora_fin', null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('id_ruta', models.ForeignKey(db_column='id_ruta', on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='rutas.ruta')),
                ('id_tiempo_cliente', models.ForeignKey(db_column='id_tiempo_cliente', default=1, on_delete=django.db.models.deletion.PROTECT, to='core.tiempocliente')),
                ('nit_cliente', models.ForeignKey(db_column='nit_cliente', on_delete=django.db.models.deletion.PROTECT, to='maestros.cliente')),
                ('resultado_visita', models.ForeignKey(db_column='resultado_visita', default='PENDIENTE', on_delete=django.db.models.deletion.PROTECT, to='core.resultadovisita')),
            ],
            options={
                'verbose_name': 'Cliente en Ruta',
                'verbose_name_plural': 'Clientes en Ruta',
                'ordering': ['id_ruta', 'orden_visita'],
                'unique_together': {('id_ruta', 'nit_cliente')},
            },
        ),
    ]
